blog/urls.py
from django.urls import path

from blog.views import (PostCreateView, PostDeleteView, PostDetailView,
                        PostListView, PostUpdateView)

app_name = "blog"


urlpatterns = [
    path("", PostListView.as_view(), name="blog"),
    path("<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("create/", PostCreateView.as_view(), name="post_create"),
    path("<int:pk>/edit/", PostUpdateView.as_view(), name="post_update"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import (ContactView, ProductCategoryView, ProductCreateView,
                           ProductDeleteView, ProductDetailView,
                           ProductListView, ProductUpdateView)

app_name = "catalog"


urlpatterns = [
    path("contacts/", ContactView.as_view(), name="contact"),
    path("home/", ProductListView.as_view(), name="home"),
    path("products/<int:pk>/", cache_page(5 * 60)(ProductDetailView.as_view()), name="product_detail"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("products/<str:category_slug>/", ProductCategoryView.as_view(), name="product_category"),
]

djangosky/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    """Класс для постов в блоге."""

    title = models.CharField(max_length=200, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Содержание")
    preview = models.ImageField(upload_to="posts/image", blank=True, null=True, verbose_name="Изображение")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    published = models.BooleanField(default=True, verbose_name="Опубликовано")
    count_views = models.IntegerField(default=0, verbose_name="Количество просмотров")

    def __str__(self):
        """Возвращает заголовок поста."""
        return f"{self.title}."

    class Meta:
        """Определение настроек модели поста."""

        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["-created_at", "title"]

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    """Класс для категорий товаров."""

    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        """Возвращает имя категории."""
        return self.name

    class Meta:
        """Определение настроек модели категории."""

        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Product(models.Model):
    """Класс для товаров с указанием категории и цены."""

    name = models.CharField(max_length=100, verbose_name="Наименование")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(upload_to="products/image", blank=True, null=True, verbose_name="Изображение")
    category = models.ForeignKey(
        verbose_name="Категория", to=Category, on_delete=models.CASCADE, related_name="products"
    )
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    created_at = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, blank=True, verbose_name="Дата изменения")
    published = models.BooleanField(default=False, verbose_name="Опубликовано")
    owner = models.ForeignKey(User, verbose_name="владелец", on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        """Возвращает имя товара, категорию и цену."""
        return f"{self.name} {self.category} {self.price}.руб."

    class Meta:
        """Определение настроек модели продукта."""

        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["-created_at", "name", "category", "price"]
        permissions = (("can_unpublish_product", "Can unpublish product"),)

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator

from .models import Product

WORDS_LIST_EXCLUDE = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]


class ProductForm(forms.ModelForm):
    name = forms.CharField(max_length=100, validators=[MaxLengthValidator(100)])
    description = forms.CharField(widget=forms.Textarea)
    price = forms.IntegerField()

    class Meta:
        model = Product
        exclude = ["created_at", "updated_at", "owner"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({"class": "form-control", "placeholder": "Наименование продукта"})
        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Описание продукта", "rows": 5}
        )
        self.fields["price"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Цена продукта", "type": "number", "min": 0, "step": 10}
        )

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price < 0:
            raise ValidationError("Цена не может быть отрицательной")
        return price

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name")
        description = cleaned_data.get("description")

        for word in name.lower().split():
            if word in WORDS_LIST_EXCLUDE:
                self.add_error("name", f"Наименование не может содержать слово {word}")

        for word in description.lower().split():
            if word in WORDS_LIST_EXCLUDE:
                self.add_error("description", f"Описание не может содержать слово {word}")


class ProductModeratorForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = [
            "published",
        ]

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

# Create your views here.
from .models import Post


class PostListView(ListView):
    """Список публичных постов."""

    model = Post

    def get_queryset(self):
        return Post.objects.filter(published=True)


class PostDetailView(DetailView):
    """Детальный просмотр поста."""

    model = Post

    def get_object(self):
        """Увеличивает счетчик просмотров поста."""
        obj = super().get_object()
        obj.count_views += 1
        obj.save()
        return obj


class PostCreateView(CreateView):
    """Создание нового поста."""

    model = Post
    fields = ("title", "content", "preview")
    success_url = reverse_lazy("blog:blog")


class PostUpdateView(UpdateView):
    """Редактирование поста."""

    model = Post
    fields = ("title", "content", "preview")

    def get_success_url(self):
        """Перенаправляет на страницу просмотра поста после редактирования."""
        return reverse_lazy("blog:post_detail", args=[self.object.id])


class PostDeleteView(DeleteView):
    """Удаление поста."""

    model = Post
    success_url = reverse_lazy("blog:blog")

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)

from .forms import ProductForm, ProductModeratorForm
from .models import Category, Product
from .services import product_list, products_list_for_category


class ProductListView(ListView):
    """Список всех продуктов."""

    model = Product

    def get_queryset(self):
        return product_list()


class ProductCategoryView(ListView):
    """Список продуктов по категории."""

    model = Category
    template_name = "catalog/product_categories.html"

    def get_queryset(self):
        category = get_object_or_404(Category, name=self.kwargs["category_slug"])
        return products_list_for_category(category.pk)


class ProductCreateView(LoginRequiredMixin, CreateView):
    """Создание нового продукта."""

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        product = form.save()
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование продукта."""

    model = Product
    form_class = ProductForm

    def get_success_url(self):
        """Перенаправляет на страницу просмотра продукта после редактирования."""
        return reverse_lazy("catalog:product_detail", args=[self.object.id])

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("catalog.can_unpublish_product"):
            return ProductModeratorForm
        else:
            raise PermissionDenied("You don't have permission to edit this product.")


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление продукта."""

    model = Product
    success_url = reverse_lazy("catalog:home")

    def post(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        user = self.request.user
        if user == self.product.owner or user.has_perm("catalog.can_delete_product"):
            product.delete()
            return redirect("catalog:home")
        else:
            return HttpResponseForbidden("У вас нет прав для исключения студента.")


class ProductDetailView(LoginRequiredMixin, DetailView):
    """Детальный просмотр продукта."""

    model = Product
    form_class = ProductForm


class ContactView(TemplateView):
    """Страница контактов."""

    template_name = "catalog/contact.html"
    extra_context = {"title": "Контакты"}

    def get_context_data(self, **kwargs):
        """Добавляет контекст с данными для отображения в шаблоне."""
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        """Отправляет сообщение сб обратной связи."""
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")
        print(f"You have new message from {name}({email}): {message}")
        return super().get(request, *args, **kwargs)

catalog/templates/blog/post_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <form class="row" method="POST" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">

                        {% csrf_token %}
                        <p class="card-text"> Действительно удалить? {{   object.title }}> </p>
                        <button type="submit" class="btn btn-primary ">
                            Удалить
                        </button>
                        <a type="submit" class="btn btn-primary " href="{%  url 'blog:post_detail' post.pk %} "> назад </a>

                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

catalog/templates/blog/post_detail.html
{% extends 'catalog/base.html' %}
{% load image_tags %}
{% block title %}{{ object.name }}{% endblock %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <a class="btn btn-primary" href="{% url 'blog:post_create' %}" role="button">Создать запись </a>
    </div>
    <div class="container py-3">
        <div class="text-center">
            <div class="col">
                <div class="card-header py-3">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    <img src="{{ object.preview | image_path }}" alt="{{ object.title }}" class="card-img-top">
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4"></li>
                        <li>- {{ object.content }}</li>
                    </ul>
                    <a type="button" class="btn btn-primary " href="{% url 'blog:post_update' post.pk %}"> Изменить</a>
                    <a type="button" class="btn btn-primary " href="{% url 'blog:post_delete' post.pk %}"> Удалить</a>

                    <li class="inline-list__item inline-list__item_bullet">
                        <span class="question__views-count">
                        {{ post.count_views }} просмотра </span>

                    </li>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/blog/post_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <form class="row" method="POST" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary ">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

catalog/templates/blog/post_list.html
{% extends 'catalog/base.html' %}
{% load image_tags %}
{% block title %} Блоговая страница {% endblock %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <a class="btn btn-primary" href="{% url 'blog:post_create' %}" role="button">Создать запись </a>
    </div>
    <div class="container py-3">
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            {% for post in object_list %}
                <div class="col">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-header py-3">
                            <a class="text-muted" href="/blogs/{{ post.id }}/"><h4
                                    class="my-0 font-weight-normal">{{ post.title }}</h4></a>
                            <img src="{{ post.preview| image_path }}">
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled mt-3 mb-4">
                                <li>- {{ post.content|truncatechars:100 }}</li>
                                <li class="inline-list__item inline-list__item_bullet">
                        <span class="question__views-count">
                        {{ post.count_views }} просмотра </span>
                                </li>
                                <li>
                                    <a class="btn btn-primary" href="{% url 'blog:post_detail' post.pk %}" role="button">
                                        Просмотр
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}